spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl_auto: create
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "health"
      base-path: "/admin"
  endpoint:
    health:
      show-details: always
#logging:
#  level:
#    root: INFO
    